networks:
  default: mainnet-fork

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.2.0

compiler:
  solc:
    version: 0.6.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.2.0"
